macro(add_compiled_tests_from_folder test_folder prefix tester args will_fail)
    find_all_k_files(tests ${test_folder})
    foreach(k_file ${tests})
        get_filename_component(filename ${k_file} NAME_WE)
        set(test_name ${prefix}${filename})
        set(compiler_args "${k_file} ${k_file}.ll ${args}")
        add_test(NAME ${test_name} COMMAND sh -c "${tester} ${compiler_args};clang ${k_file}.ll -o ${k_file}.bin;${k_file}.bin" )
        set_tests_properties(${test_name} PROPERTIES WILL_FAIL ${will_fail})
    endforeach()
endmacro()