macro(add_tests_from_folder test_folder prefix tester args)
    find_all_k_files(tests ${test_folder})
    foreach(k_file ${tests})
        MESSAGE(${k_file})
        get_filename_component(filename ${k_file} NAME_WE)
        set(test_name ${prefix}${filename})
        add_test(NAME ${test_name} COMMAND ${tester} ${k_file} ${args})
        set_tests_properties(${test_name} PROPERTIES WILL_FAIL FALSE)
    endforeach()
endmacro()