include(ExternalProject)

set(AST_NODE_HEADER "${KLANG_INCLUDE_DIR}/AST/ASTNodes.h")

file(GLOB files "${KLANG_INCLUDE_DIR}/AST/Nodes/*.h")
file(WRITE "${AST_NODE_HEADER}" "#pragma once\n")
file(APPEND "${AST_NODE_HEADER}" "\n// This file is automatically generated. Do not edit.\n\n")
foreach(file ${files})
    string(REPLACE "${KLANG_INCLUDE_DIR}/" "" NODE_FILE "${file}")
    file(APPEND "${AST_NODE_HEADER}" "#include \"${NODE_FILE}\"\n")
endforeach()