macro(find_all_k_files result starting_dir)
    set(dirs "")
    set(k_files "")
    list(APPEND dirs ${starting_dir})
    list(LENGTH dirs dir_length)
    while(dir_length GREATER 0)
        list(GET dirs 0 curdir)
        file(GLOB children RELATIVE ${curdir} ${curdir}/*)
        foreach(child ${children})
            if(IS_DIRECTORY ${curdir}/${child})
                list(APPEND dirs ${curdir}/${child})
            endif()
            get_filename_component(ext ${curdir}/${child} LAST_EXT)
            string(COMPARE EQUAL "${ext}" ".k" is_k_file)
            if(is_k_file)
                list(APPEND k_files ${curdir}/${child})
            endif()
        endforeach()
        list(REMOVE_AT dirs 0)
        list(LENGTH dirs dir_length)
    endwhile()
    set(${result} ${k_files})
endmacro()